### ISSUE TITLE
incorrect dependecies 

### ISSUE THREAD

**Issue by bugslayer01** [Aditya21Gupta/BlogWebsite#1]
u are using the method-override package in ur server.js but u have not installed method-override in ur dependencies even once in ur package.json

**Comment by Aditya21Gupta** [comment]
Dear Devansh

I think you find it wrong I already installed the Method-override package.

**Comment by bugslayer01** [comment]
kidhar kia hai
![image](https://github.com/Aditya21Gupta/BlogWebsite/assets/65941949/59152044-4af4-427d-bbb7-a534b61db3c1)

**Comment by bugslayer01** [comment]
install using this

![image](https://github.com/Aditya21Gupta/BlogWebsite/assets/65941949/12e55a9f-2573-4ce0-b994-91354f234c9d)

**Comment by Aditya21Gupta** [comment]
Dear Devansh

May be I uploaded this file before installing that.
But I already installed it and my code is working completely.

Thanks and Regards
Aditya Gupta
